### ISSUE TITLE
Implement `std::error::Error` for `BufanyError`

### ISSUE THREAD

**Issue by srdtrk** [noislabs/anybuf#20]
It makes this error easier to import and handle from external crates. Only thing that has to be implemented is `fmt::Display` since debug is already implemented. I'm happy to open a PR if agreed.

**Comment by webmaster128** [comment]
Sounds good, go for it.

While you are on it, could you also add a default feature "std" and feature-gate the implementation? I know std::error::Error is an issue for our no_std friends which might like this library at some point.

**Comment by webmaster128** [comment]
Released as part of 0.5.0. Thanks a lot!
